galaxy_info:
  author: Anton Markelov
  description: Role to install prometheus node exporter
  company: United Traders
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 7
      - 8
  galaxy_tags:
    - prometheus
    - monitoring
